# Generated by Django 5.0.2 on 2024-05-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_instructors_instructors_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructors',
            old_name='courses',
            new_name='courses_list',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.instructors'),
            preserve_default=False,
        ),
    ]
