# Generated by Django 5.0.2 on 2024-05-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_courses_instructors_courses_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='courses_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='instructors', to='courses.course'),
        ),
    ]
