# Generated by Django 5.0.2 on 2024-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_instructors_courses_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_students',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
